/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_spring_mvc_concept_study;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
